### ISSUE TITLE
Getting No view found for id aslib_main_frame_body error when using SlidingAppCompactActivity

### ISSUE THREAD

**Issue by hex6ng** [jjhesk/BringItBackAdvanceSlidingMenu#24]
```
      java.lang.RuntimeException: Unable to start activity ComponentInfo{app.package/app.package.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f110008 (app.package:id/aslib_main_frame_body) for fragment EventsRecyclerFragment{3524eb8b #1 id=0x7f110008}
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
          at android.app.ActivityThread.access$900(ActivityThread.java:177)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
          at android.os.Handler.dispatchMessage(Handler.java:102)
          at android.os.Looper.loop(Looper.java:145)
          at android.app.ActivityThread.main(ActivityThread.java:5942)
          at java.lang.reflect.Method.invoke(Native Method)
          at java.lang.reflect.Method.invoke(Method.java:372)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
       Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f110008 (app.package:id/aslib_main_frame_body) for fragment RecyclerFragment{3524eb8b #1 id=0x7f110008}
          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
          at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
          at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
          at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
          at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
          at app.package.MainActivity.onStart(MainActivity.java:248)
          at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
          at android.app.Activity.performStart(Activity.java:6329)
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
```

**Comment by hex6ng** [comment]
Never mind.  

The activity had setContentView() call to a layout that doesn't have id:aslib_main_frame_body
